namespace LaxPos.Accounting
{
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class Payables : Form
    {
        private IContainer components = null;
        private TextBox textBox2;
        private Label label8;
        private Label label6;
        private Label label5;
        private TextBox textBox1;
        private Panel panel3;
        private DataGridView Accounts_Gridview;
        private Label label7;
        private Panel Panel_Controls;
        private ComboBox ComboBox_PaymentType;
        private Label label1;
        private GroupBox groupBox1;
        private RadioButton RadioButtonAll;
        private RadioButton RadioBtn_Periodical;
        private RadioButton RadioButton_Daily;
        private DateTimePicker dateTimePicker2;
        private Label label2;
        private Button Btn_Search;
        private TextBox Txt_CashierIdBox;
        private Label label3;
        private DateTimePicker dateTimePicker1;
        private Label label4;
        private DataGridView Sales_Gridview;
        private PrintPreviewDialog printPreviewDialog1;
        private GroupBox panel2;
        private Button Btn_Export;
        private TextBox textBox4;
        private TextBox textBox3;
        private DataGridViewTextBoxColumn Column1;
        private DataGridViewTextBoxColumn Column3;
        private DataGridViewTextBoxColumn Column5;
        private DataGridViewTextBoxColumn Column6;
        private DataGridViewTextBoxColumn Column9;
        private DataGridViewTextBoxColumn Column4;
        private DataGridViewTextBoxColumn Column2;
        private DataGridViewTextBoxColumn Column7;
        private DataGridViewTextBoxColumn Column8;

        public Payables()
        {
            this.InitializeComponent();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            DataGridViewCellStyle style = new DataGridViewCellStyle();
            DataGridViewCellStyle style2 = new DataGridViewCellStyle();
            ComponentResourceManager manager = new ComponentResourceManager(typeof(Payables));
            this.textBox2 = new TextBox();
            this.label8 = new Label();
            this.label6 = new Label();
            this.label5 = new Label();
            this.textBox1 = new TextBox();
            this.panel3 = new Panel();
            this.Accounts_Gridview = new DataGridView();
            this.label7 = new Label();
            this.Panel_Controls = new Panel();
            this.ComboBox_PaymentType = new ComboBox();
            this.label1 = new Label();
            this.groupBox1 = new GroupBox();
            this.RadioButtonAll = new RadioButton();
            this.RadioBtn_Periodical = new RadioButton();
            this.RadioButton_Daily = new RadioButton();
            this.dateTimePicker2 = new DateTimePicker();
            this.label2 = new Label();
            this.Btn_Search = new Button();
            this.Txt_CashierIdBox = new TextBox();
            this.label3 = new Label();
            this.dateTimePicker1 = new DateTimePicker();
            this.label4 = new Label();
            this.Sales_Gridview = new DataGridView();
            this.printPreviewDialog1 = new PrintPreviewDialog();
            this.panel2 = new GroupBox();
            this.Btn_Export = new Button();
            this.textBox4 = new TextBox();
            this.textBox3 = new TextBox();
            this.Column8 = new DataGridViewTextBoxColumn();
            this.Column7 = new DataGridViewTextBoxColumn();
            this.Column2 = new DataGridViewTextBoxColumn();
            this.Column4 = new DataGridViewTextBoxColumn();
            this.Column9 = new DataGridViewTextBoxColumn();
            this.Column6 = new DataGridViewTextBoxColumn();
            this.Column5 = new DataGridViewTextBoxColumn();
            this.Column3 = new DataGridViewTextBoxColumn();
            this.Column1 = new DataGridViewTextBoxColumn();
            this.panel3.SuspendLayout();
            ((ISupportInitialize) this.Accounts_Gridview).BeginInit();
            this.Panel_Controls.SuspendLayout();
            this.groupBox1.SuspendLayout();
            ((ISupportInitialize) this.Sales_Gridview).BeginInit();
            this.panel2.SuspendLayout();
            base.SuspendLayout();
            this.textBox2.Font = new Font("Microsoft Sans Serif", 14f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.textBox2.Location = new Point(0xc1, 0x29);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new Size(0xae, 0x1d);
            this.textBox2.TabIndex = 13;
            this.textBox2.TextAlign = HorizontalAlignment.Center;
            this.label8.AutoSize = true;
            this.label8.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label8.Location = new Point(0xc6, 0x12);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x39, 20);
            this.label8.TabIndex = 4;
            this.label8.Text = "Mpesa";
            this.label6.AutoSize = true;
            this.label6.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label6.Location = new Point(0x10, 0x12);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0x2e, 20);
            this.label6.TabIndex = 2;
            this.label6.Text = "Cash";
            this.label5.AutoSize = true;
            this.label5.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label5.Location = new Point(0x18b, 0x12);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x33, 20);
            this.label5.TabIndex = 1;
            this.label5.Text = "Cards";
            this.textBox1.Font = new Font("Microsoft Sans Serif", 14f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.textBox1.Location = new Point(7, 0x29);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new Size(0xae, 0x1d);
            this.textBox1.TabIndex = 0;
            this.textBox1.TextAlign = HorizontalAlignment.Center;
            this.panel3.Controls.Add(this.Accounts_Gridview);
            this.panel3.Dock = DockStyle.Fill;
            this.panel3.Location = new Point(0, 0x3e);
            this.panel3.Name = "panel3";
            this.panel3.Size = new Size(0x3cc, 0x132);
            this.panel3.TabIndex = 0x18;
            this.Accounts_Gridview.AllowUserToAddRows = false;
            this.Accounts_Gridview.AllowUserToDeleteRows = false;
            this.Accounts_Gridview.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            this.Accounts_Gridview.BackgroundColor = SystemColors.Window;
            this.Accounts_Gridview.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            DataGridViewColumn[] dataGridViewColumns = new DataGridViewColumn[9];
            dataGridViewColumns[0] = this.Column1;
            dataGridViewColumns[1] = this.Column3;
            dataGridViewColumns[2] = this.Column5;
            dataGridViewColumns[3] = this.Column6;
            dataGridViewColumns[4] = this.Column9;
            dataGridViewColumns[5] = this.Column4;
            dataGridViewColumns[6] = this.Column2;
            dataGridViewColumns[7] = this.Column7;
            dataGridViewColumns[8] = this.Column8;
            this.Accounts_Gridview.Columns.AddRange(dataGridViewColumns);
            this.Accounts_Gridview.Dock = DockStyle.Fill;
            this.Accounts_Gridview.Location = new Point(0, 0);
            this.Accounts_Gridview.Name = "Accounts_Gridview";
            this.Accounts_Gridview.ReadOnly = true;
            this.Accounts_Gridview.RowHeadersVisible = false;
            this.Accounts_Gridview.Size = new Size(0x3cc, 0x132);
            this.Accounts_Gridview.TabIndex = 0x18;
            this.label7.AutoSize = true;
            this.label7.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.label7.Location = new Point(590, 0x12);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0x2c, 20);
            this.label7.TabIndex = 12;
            this.label7.Text = "Total";
            this.Panel_Controls.Controls.Add(this.ComboBox_PaymentType);
            this.Panel_Controls.Controls.Add(this.label1);
            this.Panel_Controls.Controls.Add(this.groupBox1);
            this.Panel_Controls.Controls.Add(this.dateTimePicker2);
            this.Panel_Controls.Controls.Add(this.label2);
            this.Panel_Controls.Controls.Add(this.Btn_Search);
            this.Panel_Controls.Controls.Add(this.Txt_CashierIdBox);
            this.Panel_Controls.Controls.Add(this.label3);
            this.Panel_Controls.Controls.Add(this.dateTimePicker1);
            this.Panel_Controls.Controls.Add(this.label4);
            this.Panel_Controls.Dock = DockStyle.Top;
            this.Panel_Controls.Location = new Point(0, 0);
            this.Panel_Controls.Name = "Panel_Controls";
            this.Panel_Controls.Size = new Size(0x3cc, 0x3e);
            this.Panel_Controls.TabIndex = 0x15;
            this.ComboBox_PaymentType.BackColor = Color.FromArgb(0xff, 0xff, 0xc0);
            this.ComboBox_PaymentType.Font = new Font("Microsoft Sans Serif", 10f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.ComboBox_PaymentType.FormattingEnabled = true;
            object[] items = new object[] { "All", "Cash", "Mpesa", "Card" };
            this.ComboBox_PaymentType.Items.AddRange(items);
            this.ComboBox_PaymentType.Location = new Point(0x283, 30);
            this.ComboBox_PaymentType.Name = "ComboBox_PaymentType";
            this.ComboBox_PaymentType.Size = new Size(0x89, 0x18);
            this.ComboBox_PaymentType.TabIndex = 20;
            this.label1.AutoSize = true;
            this.label1.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label1.ForeColor = Color.FromArgb(0, 0, 0x40);
            this.label1.Location = new Point(0x288, 5);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x7a, 0x16);
            this.label1.TabIndex = 0x13;
            this.label1.Text = "Payment Mode";
            this.groupBox1.Controls.Add(this.RadioButtonAll);
            this.groupBox1.Controls.Add(this.RadioBtn_Periodical);
            this.groupBox1.Controls.Add(this.RadioButton_Daily);
            this.groupBox1.Location = new Point(0xbf, 3);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0xee, 0x38);
            this.groupBox1.TabIndex = 0x12;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Report Frequency";
            this.RadioButtonAll.AutoSize = true;
            this.RadioButtonAll.Font = new Font("Palatino Linotype", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.RadioButtonAll.Location = new Point(9, 0x18);
            this.RadioButtonAll.Name = "RadioButtonAll";
            this.RadioButtonAll.Size = new Size(0x2f, 0x1a);
            this.RadioButtonAll.TabIndex = 2;
            this.RadioButtonAll.TabStop = true;
            this.RadioButtonAll.Text = "All";
            this.RadioButtonAll.UseVisualStyleBackColor = true;
            this.RadioBtn_Periodical.AutoSize = true;
            this.RadioBtn_Periodical.Font = new Font("Palatino Linotype", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.RadioBtn_Periodical.Location = new Point(0x8e, 0x18);
            this.RadioBtn_Periodical.Name = "RadioBtn_Periodical";
            this.RadioBtn_Periodical.Size = new Size(0x5e, 0x1a);
            this.RadioBtn_Periodical.TabIndex = 1;
            this.RadioBtn_Periodical.TabStop = true;
            this.RadioBtn_Periodical.Text = "Periodical";
            this.RadioBtn_Periodical.UseVisualStyleBackColor = true;
            this.RadioButton_Daily.AutoSize = true;
            this.RadioButton_Daily.Font = new Font("Palatino Linotype", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.RadioButton_Daily.Location = new Point(0x47, 0x18);
            this.RadioButton_Daily.Name = "RadioButton_Daily";
            this.RadioButton_Daily.Size = new Size(0x41, 0x1a);
            this.RadioButton_Daily.TabIndex = 0;
            this.RadioButton_Daily.TabStop = true;
            this.RadioButton_Daily.Text = "Daily";
            this.RadioButton_Daily.UseVisualStyleBackColor = true;
            this.dateTimePicker2.Font = new Font("Microsoft Sans Serif", 10f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.dateTimePicker2.Format = DateTimePickerFormat.Short;
            this.dateTimePicker2.Location = new Point(0x1f1, 0x22);
            this.dateTimePicker2.Name = "dateTimePicker2";
            this.dateTimePicker2.Size = new Size(0x74, 0x17);
            this.dateTimePicker2.TabIndex = 0x10;
            this.label2.AutoSize = true;
            this.label2.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label2.ForeColor = Color.FromArgb(0, 0, 0x40);
            this.label2.Location = new Point(0x10, 6);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x43, 0x16);
            this.label2.TabIndex = 11;
            this.label2.Text = "Cashier";
            this.Btn_Search.BackColor = Color.Maroon;
            this.Btn_Search.FlatStyle = FlatStyle.Flat;
            this.Btn_Search.Font = new Font("Palatino Linotype", 15f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Btn_Search.ForeColor = SystemColors.ButtonHighlight;
            this.Btn_Search.Location = new Point(0x330, 12);
            this.Btn_Search.Name = "Btn_Search";
            this.Btn_Search.Size = new Size(150, 0x29);
            this.Btn_Search.TabIndex = 0x11;
            this.Btn_Search.Text = "Search";
            this.Btn_Search.UseVisualStyleBackColor = false;
            this.Txt_CashierIdBox.BackColor = Color.FromArgb(0xff, 0xff, 0xc0);
            this.Txt_CashierIdBox.BorderStyle = BorderStyle.FixedSingle;
            this.Txt_CashierIdBox.Font = new Font("Microsoft Sans Serif", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.Txt_CashierIdBox.Location = new Point(7, 30);
            this.Txt_CashierIdBox.Name = "Txt_CashierIdBox";
            this.Txt_CashierIdBox.Size = new Size(0xa9, 0x1a);
            this.Txt_CashierIdBox.TabIndex = 12;
            this.label3.AutoSize = true;
            this.label3.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label3.ForeColor = Color.FromArgb(0, 0, 0x40);
            this.label3.Location = new Point(0x1b9, 5);
            this.label3.Name = "label3";
            this.label3.Size = new Size(50, 0x16);
            this.label3.TabIndex = 13;
            this.label3.Text = "From";
            this.dateTimePicker1.Font = new Font("Microsoft Sans Serif", 10f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.dateTimePicker1.Format = DateTimePickerFormat.Short;
            this.dateTimePicker1.Location = new Point(0x1f1, 6);
            this.dateTimePicker1.Name = "dateTimePicker1";
            this.dateTimePicker1.Size = new Size(0x74, 0x17);
            this.dateTimePicker1.TabIndex = 15;
            this.label4.AutoSize = true;
            this.label4.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.label4.ForeColor = Color.FromArgb(0, 0, 0x40);
            this.label4.Location = new Point(0x1b9, 0x20);
            this.label4.Name = "label4";
            this.label4.Size = new Size(30, 0x16);
            this.label4.TabIndex = 14;
            this.label4.Text = "To";
            this.Sales_Gridview.AllowUserToAddRows = false;
            this.Sales_Gridview.AllowUserToDeleteRows = false;
            this.Sales_Gridview.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            this.Sales_Gridview.BackgroundColor = SystemColors.ButtonHighlight;
            style.Alignment = DataGridViewContentAlignment.MiddleLeft;
            style.BackColor = SystemColors.ControlText;
            style.Font = new Font("Microsoft Sans Serif", 11f, FontStyle.Regular, GraphicsUnit.Point, 0);
            style.ForeColor = SystemColors.ButtonHighlight;
            style.SelectionBackColor = SystemColors.Highlight;
            style.SelectionForeColor = SystemColors.HighlightText;
            style.WrapMode = DataGridViewTriState.True;
            this.Sales_Gridview.ColumnHeadersDefaultCellStyle = style;
            this.Sales_Gridview.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.Sales_Gridview.Dock = DockStyle.Fill;
            this.Sales_Gridview.EnableHeadersVisualStyles = false;
            this.Sales_Gridview.Location = new Point(0, 0);
            this.Sales_Gridview.Name = "Sales_Gridview";
            this.Sales_Gridview.ReadOnly = true;
            this.Sales_Gridview.RowHeadersVisible = false;
            style2.Font = new Font("Segoe UI", 12f, FontStyle.Regular, GraphicsUnit.Point, 0);
            style2.ForeColor = Color.Black;
            this.Sales_Gridview.RowsDefaultCellStyle = style2;
            this.Sales_Gridview.Size = new Size(0x3cc, 0x170);
            this.Sales_Gridview.TabIndex = 0x17;
            this.printPreviewDialog1.AutoScrollMargin = new Size(0, 0);
            this.printPreviewDialog1.AutoScrollMinSize = new Size(0, 0);
            this.printPreviewDialog1.ClientSize = new Size(400, 300);
            this.printPreviewDialog1.Enabled = true;
            this.printPreviewDialog1.Icon = (Icon) manager.GetObject("printPreviewDialog1.Icon");
            this.printPreviewDialog1.Name = "printPreviewDialog1";
            this.printPreviewDialog1.Visible = false;
            this.panel2.Controls.Add(this.textBox2);
            this.panel2.Controls.Add(this.label7);
            this.panel2.Controls.Add(this.Btn_Export);
            this.panel2.Controls.Add(this.textBox4);
            this.panel2.Controls.Add(this.textBox3);
            this.panel2.Controls.Add(this.label8);
            this.panel2.Controls.Add(this.label6);
            this.panel2.Controls.Add(this.label5);
            this.panel2.Controls.Add(this.textBox1);
            this.panel2.Dock = DockStyle.Bottom;
            this.panel2.Location = new Point(0, 0x170);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(0x3cc, 0x52);
            this.panel2.TabIndex = 0x16;
            this.panel2.TabStop = false;
            this.panel2.Text = "Total Summary";
            this.Btn_Export.BackColor = Color.Maroon;
            this.Btn_Export.FlatStyle = FlatStyle.Flat;
            this.Btn_Export.Font = new Font("Palatino Linotype", 15f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Btn_Export.ForeColor = SystemColors.ButtonHighlight;
            this.Btn_Export.Location = new Point(0x330, 0x1d);
            this.Btn_Export.Name = "Btn_Export";
            this.Btn_Export.Size = new Size(150, 0x29);
            this.Btn_Export.TabIndex = 11;
            this.Btn_Export.Text = "Export ";
            this.Btn_Export.UseVisualStyleBackColor = false;
            this.textBox4.Font = new Font("Microsoft Sans Serif", 14f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.textBox4.Location = new Point(0x243, 0x29);
            this.textBox4.Name = "textBox4";
            this.textBox4.Size = new Size(0xd8, 0x1d);
            this.textBox4.TabIndex = 9;
            this.textBox4.TextAlign = HorizontalAlignment.Center;
            this.textBox3.Font = new Font("Microsoft Sans Serif", 14f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.textBox3.Location = new Point(0x181, 0x29);
            this.textBox3.Name = "textBox3";
            this.textBox3.Size = new Size(0xae, 0x1d);
            this.textBox3.TabIndex = 7;
            this.textBox3.TextAlign = HorizontalAlignment.Center;
            this.Column8.HeaderText = "Counter";
            this.Column8.Name = "Column8";
            this.Column8.ReadOnly = true;
            this.Column7.HeaderText = "Cashier";
            this.Column7.Name = "Column7";
            this.Column7.ReadOnly = true;
            this.Column2.HeaderText = "Date";
            this.Column2.Name = "Column2";
            this.Column2.ReadOnly = true;
            this.Column4.HeaderText = "Balance";
            this.Column4.Name = "Column4";
            this.Column4.ReadOnly = true;
            this.Column9.HeaderText = "TotalPaid";
            this.Column9.Name = "Column9";
            this.Column9.ReadOnly = true;
            this.Column6.HeaderText = "Method";
            this.Column6.Name = "Column6";
            this.Column6.ReadOnly = true;
            this.Column5.HeaderText = "SubAmount";
            this.Column5.Name = "Column5";
            this.Column5.ReadOnly = true;
            this.Column3.HeaderText = "AccType";
            this.Column3.Name = "Column3";
            this.Column3.ReadOnly = true;
            this.Column1.HeaderText = "TransactionNo";
            this.Column1.Name = "Column1";
            this.Column1.ReadOnly = true;
            base.AutoScaleMode = AutoScaleMode.None;
            base.ClientSize = new Size(0x3cc, 450);
            base.Controls.Add(this.panel3);
            base.Controls.Add(this.Panel_Controls);
            base.Controls.Add(this.Sales_Gridview);
            base.Controls.Add(this.panel2);
            this.DoubleBuffered = true;
            this.Font = new Font("Microsoft Sans Serif", 11f, FontStyle.Regular, GraphicsUnit.Point, 0);
            base.FormBorderStyle = FormBorderStyle.None;
            base.Name = "Payables";
            this.Text = "Payabpes";
            this.panel3.ResumeLayout(false);
            ((ISupportInitialize) this.Accounts_Gridview).EndInit();
            this.Panel_Controls.ResumeLayout(false);
            this.Panel_Controls.PerformLayout();
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            ((ISupportInitialize) this.Sales_Gridview).EndInit();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            base.ResumeLayout(false);
        }
    }
}

