namespace LaxPos.Customers
{
    using Bunifu.Framework.UI;
    using LaxPos;
    using LaxPos.LaxPosFiles;
    using MySql.Data.MySqlClient;
    using System;
    using System.ComponentModel;
    using System.Drawing;
    using System.Windows.Forms;

    public class InvoicedCustomers : BunifuForm
    {
        private readonly DatabaseConfiguration Db = new DatabaseConfiguration();
        private IContainer components = null;
        private TabControl TabControl_ManageCustomers;
        private TabPage TabPage_NewCustomer;
        private GroupBox groupBox1;
        private TextBox textBox6;
        private Label label6;
        private GroupBox groupBox4;
        private RadioButton radioButton3;
        private RadioButton radioButton4;
        private GroupBox groupBox3;
        private RadioButton radioButton5;
        private RadioButton radioButton6;
        private TextBox textBox5;
        private Label label5;
        private TextBox textBox4;
        private TextBox textBox2;
        private Button Btn_Clear;
        private Button Btn_AddCustomer;
        private GroupBox groupBox2;
        private RadioButton radioButton2;
        private RadioButton radioButton1;
        private Label label1;
        private Label label4;
        private TextBox textBox1;
        private Label label2;
        private TabPage TabPage_EditCustomer;
        private GroupBox groupBox9;
        private TextBox textBox13;
        private Label label13;
        private GroupBox groupBox10;
        private RadioButton radioButton13;
        private RadioButton radioButton14;
        private GroupBox groupBox11;
        private RadioButton radioButton15;
        private RadioButton radioButton16;
        private TextBox textBox14;
        private Label label14;
        private TextBox textBox15;
        private TextBox textBox16;
        private Label label15;
        private TextBox textBox17;
        private Button Btn_Cancel;
        private Button Btn_Update;
        private GroupBox groupBox12;
        private RadioButton radioButton17;
        private RadioButton radioButton18;
        private Label label16;
        private Label label17;
        private GroupBox groupBox5;
        private Panel panel1;
        private Button Btn_Search;
        private Label label22;
        private TextBox textBox22;
        private TextBox textBox12;
        private TextBox textBox11;
        private TextBox textBox10;
        private TextBox textBox9;
        private TextBox textBox8;
        private TextBox textBox21;
        private Label label21;
        private TextBox textBox20;
        private Label label20;
        private TextBox textBox19;
        private Label label19;
        private TextBox textBox7;
        private Label label7;
        private Label label8;
        private Label label9;
        private Label label10;
        private Label label11;
        private Label label12;
        private TabPage Tab_Page_CustomerAccount;
        private Panel panel3;
        private GroupBox groupBox6;
        private TextBox textBox25;
        private TextBox textBox26;
        private TextBox textBox27;
        private TextBox textBox28;
        private TextBox textBox29;
        private TextBox textBox30;
        private Label label25;
        private TextBox textBox31;
        private Label label26;
        private TextBox textBox32;
        private Label label27;
        private TextBox textBox33;
        private Label label28;
        private Label label29;
        private Label label30;
        private Label label31;
        private Label label32;
        private Label label33;
        private Panel panel2;
        private Button Btn_searchAccount;
        private Label label23;
        private TextBox textBox23;
        private TabPage TabPage_CustomersList;
        private Panel panel5;
        private Panel panel6;
        private DataGridView dataGridView1;
        private DataGridViewTextBoxColumn Column1;
        private DataGridViewTextBoxColumn Column2;
        private DataGridViewTextBoxColumn Column3;
        private DataGridViewTextBoxColumn Column4;
        private DataGridViewTextBoxColumn Column5;
        private DataGridViewTextBoxColumn Column6;
        private DataGridViewTextBoxColumn Column7;
        private DataGridViewTextBoxColumn Column8;
        private DataGridViewTextBoxColumn Column9;
        private DataGridViewTextBoxColumn Column10;
        private TextBox textBox18;
        private Label label18;
        private Button Btn_RefreshInvoiced_Customers;

        public InvoicedCustomers()
        {
            this.InitializeComponent();
        }

        private void Btn_AddCustomer_Click(object sender, EventArgs e)
        {
            if (((this.textBox1.Text == "") || ((this.textBox2.Text == "") || ((this.textBox4.Text == "") || ((this.textBox5.Text == "") || (this.textBox6.Text == ""))))) || (!this.radioButton1.Checked && !this.radioButton2.Checked))
            {
                MessageBox.Show("Incomplete Customer Details", "Message Box", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
            }
            else if (!(this.radioButton4.Checked || this.radioButton3.Checked))
            {
                MessageBox.Show("Select Invoice Status", "Message Box", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
            }
            else if (!(this.radioButton1.Checked || this.radioButton2.Checked))
            {
                MessageBox.Show("Select Customer's Gender", "Message Box", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
            }
            else if (this.radioButton5.Checked || this.radioButton6.Checked)
            {
                this.InsertCustomer();
            }
            else
            {
                MessageBox.Show("Select Customer Type", "Message Box", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
            }
        }

        private void Btn_RefreshInvoiced_Customers_Click(object sender, EventArgs e)
        {
            this.LoadInvoicedCustomers();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.TabControl_ManageCustomers = new TabControl();
            this.TabPage_NewCustomer = new TabPage();
            this.groupBox1 = new GroupBox();
            this.textBox6 = new TextBox();
            this.label6 = new Label();
            this.groupBox4 = new GroupBox();
            this.radioButton3 = new RadioButton();
            this.radioButton4 = new RadioButton();
            this.groupBox3 = new GroupBox();
            this.radioButton5 = new RadioButton();
            this.radioButton6 = new RadioButton();
            this.textBox5 = new TextBox();
            this.label5 = new Label();
            this.textBox4 = new TextBox();
            this.textBox2 = new TextBox();
            this.Btn_Clear = new Button();
            this.Btn_AddCustomer = new Button();
            this.groupBox2 = new GroupBox();
            this.radioButton2 = new RadioButton();
            this.radioButton1 = new RadioButton();
            this.label1 = new Label();
            this.label4 = new Label();
            this.textBox1 = new TextBox();
            this.label2 = new Label();
            this.TabPage_EditCustomer = new TabPage();
            this.groupBox9 = new GroupBox();
            this.textBox13 = new TextBox();
            this.label13 = new Label();
            this.groupBox10 = new GroupBox();
            this.radioButton13 = new RadioButton();
            this.radioButton14 = new RadioButton();
            this.groupBox11 = new GroupBox();
            this.radioButton15 = new RadioButton();
            this.radioButton16 = new RadioButton();
            this.textBox14 = new TextBox();
            this.label14 = new Label();
            this.textBox15 = new TextBox();
            this.textBox16 = new TextBox();
            this.label15 = new Label();
            this.textBox17 = new TextBox();
            this.Btn_Cancel = new Button();
            this.Btn_Update = new Button();
            this.groupBox12 = new GroupBox();
            this.radioButton17 = new RadioButton();
            this.radioButton18 = new RadioButton();
            this.label16 = new Label();
            this.label17 = new Label();
            this.textBox18 = new TextBox();
            this.label18 = new Label();
            this.groupBox5 = new GroupBox();
            this.panel1 = new Panel();
            this.Btn_Search = new Button();
            this.label22 = new Label();
            this.textBox22 = new TextBox();
            this.textBox12 = new TextBox();
            this.textBox11 = new TextBox();
            this.textBox10 = new TextBox();
            this.textBox9 = new TextBox();
            this.textBox8 = new TextBox();
            this.textBox21 = new TextBox();
            this.label21 = new Label();
            this.textBox20 = new TextBox();
            this.label20 = new Label();
            this.textBox19 = new TextBox();
            this.label19 = new Label();
            this.textBox7 = new TextBox();
            this.label7 = new Label();
            this.label8 = new Label();
            this.label9 = new Label();
            this.label10 = new Label();
            this.label11 = new Label();
            this.label12 = new Label();
            this.Tab_Page_CustomerAccount = new TabPage();
            this.panel3 = new Panel();
            this.groupBox6 = new GroupBox();
            this.textBox25 = new TextBox();
            this.textBox26 = new TextBox();
            this.textBox27 = new TextBox();
            this.textBox28 = new TextBox();
            this.textBox29 = new TextBox();
            this.textBox30 = new TextBox();
            this.label25 = new Label();
            this.textBox31 = new TextBox();
            this.label26 = new Label();
            this.textBox32 = new TextBox();
            this.label27 = new Label();
            this.textBox33 = new TextBox();
            this.label28 = new Label();
            this.label29 = new Label();
            this.label30 = new Label();
            this.label31 = new Label();
            this.label32 = new Label();
            this.label33 = new Label();
            this.panel2 = new Panel();
            this.Btn_searchAccount = new Button();
            this.label23 = new Label();
            this.textBox23 = new TextBox();
            this.TabPage_CustomersList = new TabPage();
            this.dataGridView1 = new DataGridView();
            this.Column1 = new DataGridViewTextBoxColumn();
            this.Column2 = new DataGridViewTextBoxColumn();
            this.Column3 = new DataGridViewTextBoxColumn();
            this.Column4 = new DataGridViewTextBoxColumn();
            this.Column5 = new DataGridViewTextBoxColumn();
            this.Column6 = new DataGridViewTextBoxColumn();
            this.Column7 = new DataGridViewTextBoxColumn();
            this.Column8 = new DataGridViewTextBoxColumn();
            this.Column9 = new DataGridViewTextBoxColumn();
            this.Column10 = new DataGridViewTextBoxColumn();
            this.panel6 = new Panel();
            this.panel5 = new Panel();
            this.Btn_RefreshInvoiced_Customers = new Button();
            this.TabControl_ManageCustomers.SuspendLayout();
            this.TabPage_NewCustomer.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.groupBox4.SuspendLayout();
            this.groupBox3.SuspendLayout();
            this.groupBox2.SuspendLayout();
            this.TabPage_EditCustomer.SuspendLayout();
            this.groupBox9.SuspendLayout();
            this.groupBox10.SuspendLayout();
            this.groupBox11.SuspendLayout();
            this.groupBox12.SuspendLayout();
            this.groupBox5.SuspendLayout();
            this.panel1.SuspendLayout();
            this.Tab_Page_CustomerAccount.SuspendLayout();
            this.panel3.SuspendLayout();
            this.groupBox6.SuspendLayout();
            this.panel2.SuspendLayout();
            this.TabPage_CustomersList.SuspendLayout();
            ((ISupportInitialize) this.dataGridView1).BeginInit();
            this.panel6.SuspendLayout();
            base.SuspendLayout();
            this.TabControl_ManageCustomers.Controls.Add(this.TabPage_NewCustomer);
            this.TabControl_ManageCustomers.Controls.Add(this.TabPage_EditCustomer);
            this.TabControl_ManageCustomers.Controls.Add(this.Tab_Page_CustomerAccount);
            this.TabControl_ManageCustomers.Controls.Add(this.TabPage_CustomersList);
            this.TabControl_ManageCustomers.Dock = DockStyle.Fill;
            this.TabControl_ManageCustomers.Font = new Font("Microsoft Sans Serif", 10f, FontStyle.Regular, GraphicsUnit.Point, 0);
            this.TabControl_ManageCustomers.HotTrack = true;
            this.TabControl_ManageCustomers.ItemSize = new Size(100, 0x19);
            this.TabControl_ManageCustomers.Location = new Point(0, 0);
            this.TabControl_ManageCustomers.Multiline = true;
            this.TabControl_ManageCustomers.Name = "TabControl_ManageCustomers";
            this.TabControl_ManageCustomers.Padding = new Point(0x19, 3);
            this.TabControl_ManageCustomers.SelectedIndex = 0;
            this.TabControl_ManageCustomers.Size = new Size(0x4b0, 600);
            this.TabControl_ManageCustomers.TabIndex = 9;
            this.TabControl_ManageCustomers.SelectedIndexChanged += new EventHandler(this.TabControl_ManageCustomers_SelectedIndexChanged);
            this.TabPage_NewCustomer.AutoScroll = true;
            this.TabPage_NewCustomer.Controls.Add(this.groupBox1);
            this.TabPage_NewCustomer.Location = new Point(4, 0x1d);
            this.TabPage_NewCustomer.Name = "TabPage_NewCustomer";
            this.TabPage_NewCustomer.Padding = new Padding(3);
            this.TabPage_NewCustomer.Size = new Size(0x4a8, 0x237);
            this.TabPage_NewCustomer.TabIndex = 1;
            this.TabPage_NewCustomer.Text = "New Customer";
            this.TabPage_NewCustomer.UseVisualStyleBackColor = true;
            this.groupBox1.Controls.Add(this.textBox6);
            this.groupBox1.Controls.Add(this.label6);
            this.groupBox1.Controls.Add(this.groupBox4);
            this.groupBox1.Controls.Add(this.groupBox3);
            this.groupBox1.Controls.Add(this.textBox5);
            this.groupBox1.Controls.Add(this.label5);
            this.groupBox1.Controls.Add(this.textBox4);
            this.groupBox1.Controls.Add(this.textBox2);
            this.groupBox1.Controls.Add(this.Btn_Clear);
            this.groupBox1.Controls.Add(this.Btn_AddCustomer);
            this.groupBox1.Controls.Add(this.groupBox2);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.textBox1);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Font = new Font("Palatino Linotype", 9.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.groupBox1.Location = new Point(6, 6);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new Size(0x2a6, 0x18d);
            this.groupBox1.TabIndex = 1;
            this.groupBox1.TabStop = false;
            this.groupBox1.Text = "Customer Editor Box";
            this.textBox6.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox6.Location = new Point(0x10, 0x116);
            this.textBox6.MaxLength = 10;
            this.textBox6.Name = "textBox6";
            this.textBox6.Size = new Size(0xc7, 0x1d);
            this.textBox6.TabIndex = 0x20;
            this.label6.AutoSize = true;
            this.label6.Location = new Point(0x10, 0x101);
            this.label6.Name = "label6";
            this.label6.Size = new Size(0xb2, 0x12);
            this.label6.TabIndex = 0x1f;
            this.label6.Text = "Maximu Invoicable Amount";
            this.groupBox4.Controls.Add(this.radioButton3);
            this.groupBox4.Controls.Add(this.radioButton4);
            this.groupBox4.Location = new Point(0x130, 0x18);
            this.groupBox4.Name = "groupBox4";
            this.groupBox4.Size = new Size(0xc7, 0x6f);
            this.groupBox4.TabIndex = 30;
            this.groupBox4.TabStop = false;
            this.groupBox4.Text = "Invoicing Status";
            this.radioButton3.AutoSize = true;
            this.radioButton3.Location = new Point(0x12, 0x41);
            this.radioButton3.Name = "radioButton3";
            this.radioButton3.Size = new Size(0x2d, 0x16);
            this.radioButton3.TabIndex = 1;
            this.radioButton3.TabStop = true;
            this.radioButton3.Text = "No";
            this.radioButton3.UseVisualStyleBackColor = true;
            this.radioButton4.AutoSize = true;
            this.radioButton4.Location = new Point(0x10, 0x23);
            this.radioButton4.Name = "radioButton4";
            this.radioButton4.Size = new Size(0x2f, 0x16);
            this.radioButton4.TabIndex = 0;
            this.radioButton4.TabStop = true;
            this.radioButton4.Text = "Yes";
            this.radioButton4.UseVisualStyleBackColor = true;
            this.groupBox3.Controls.Add(this.radioButton5);
            this.groupBox3.Controls.Add(this.radioButton6);
            this.groupBox3.Location = new Point(0x130, 150);
            this.groupBox3.Name = "groupBox3";
            this.groupBox3.Size = new Size(0x15a, 0x6f);
            this.groupBox3.TabIndex = 0x1d;
            this.groupBox3.TabStop = false;
            this.groupBox3.Text = "Customer Type";
            this.radioButton5.AutoSize = true;
            this.radioButton5.Location = new Point(0x10, 0x4d);
            this.radioButton5.Name = "radioButton5";
            this.radioButton5.Size = new Size(0x93, 0x16);
            this.radioButton5.TabIndex = 1;
            this.radioButton5.TabStop = true;
            this.radioButton5.Text = "Company Customer";
            this.radioButton5.UseVisualStyleBackColor = true;
            this.radioButton6.AutoSize = true;
            this.radioButton6.Location = new Point(0x10, 0x23);
            this.radioButton6.Name = "radioButton6";
            this.radioButton6.Size = new Size(0x97, 0x16);
            this.radioButton6.TabIndex = 0;
            this.radioButton6.TabStop = true;
            this.radioButton6.Text = "Individual Customer";
            this.radioButton6.UseVisualStyleBackColor = true;
            this.textBox5.Location = new Point(13, 0xda);
            this.textBox5.Name = "textBox5";
            this.textBox5.Size = new Size(0xfe, 0x19);
            this.textBox5.TabIndex = 0x1c;
            this.label5.AutoSize = true;
            this.label5.Location = new Point(13, 0x8a);
            this.label5.Name = "label5";
            this.label5.Size = new Size(0x2b, 0x12);
            this.label5.TabIndex = 0x1a;
            this.label5.Text = "Email";
            this.textBox4.Location = new Point(13, 0x9f);
            this.textBox4.Name = "textBox4";
            this.textBox4.Size = new Size(0xfe, 0x19);
            this.textBox4.TabIndex = 0x1b;
            this.textBox2.Location = new Point(13, 100);
            this.textBox2.Name = "textBox2";
            this.textBox2.Size = new Size(0xfe, 0x19);
            this.textBox2.TabIndex = 0x17;
            this.Btn_Clear.BackColor = Color.OrangeRed;
            this.Btn_Clear.FlatStyle = FlatStyle.Flat;
            this.Btn_Clear.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Btn_Clear.ForeColor = SystemColors.ButtonHighlight;
            this.Btn_Clear.Location = new Point(0x4d, 0x14e);
            this.Btn_Clear.Name = "Btn_Clear";
            this.Btn_Clear.Size = new Size(0xb1, 40);
            this.Btn_Clear.TabIndex = 0x16;
            this.Btn_Clear.Text = "Clear";
            this.Btn_Clear.UseVisualStyleBackColor = false;
            this.Btn_AddCustomer.BackColor = Color.Indigo;
            this.Btn_AddCustomer.FlatStyle = FlatStyle.Flat;
            this.Btn_AddCustomer.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Btn_AddCustomer.ForeColor = SystemColors.ButtonHighlight;
            this.Btn_AddCustomer.Location = new Point(0x135, 0x14e);
            this.Btn_AddCustomer.Name = "Btn_AddCustomer";
            this.Btn_AddCustomer.Size = new Size(0xc9, 40);
            this.Btn_AddCustomer.TabIndex = 20;
            this.Btn_AddCustomer.Text = "Add Customer";
            this.Btn_AddCustomer.UseVisualStyleBackColor = false;
            this.Btn_AddCustomer.Click += new EventHandler(this.Btn_AddCustomer_Click);
            this.groupBox2.Controls.Add(this.radioButton2);
            this.groupBox2.Controls.Add(this.radioButton1);
            this.groupBox2.Location = new Point(0x203, 0x18);
            this.groupBox2.Name = "groupBox2";
            this.groupBox2.Size = new Size(0x87, 0x6f);
            this.groupBox2.TabIndex = 0x13;
            this.groupBox2.TabStop = false;
            this.groupBox2.Text = "Customer Gender";
            this.radioButton2.AutoSize = true;
            this.radioButton2.Location = new Point(0x10, 0x4c);
            this.radioButton2.Name = "radioButton2";
            this.radioButton2.Size = new Size(0x47, 0x16);
            this.radioButton2.TabIndex = 1;
            this.radioButton2.TabStop = true;
            this.radioButton2.Text = "Female";
            this.radioButton2.UseVisualStyleBackColor = true;
            this.radioButton1.AutoSize = true;
            this.radioButton1.Location = new Point(0x10, 0x23);
            this.radioButton1.Name = "radioButton1";
            this.radioButton1.Size = new Size(0x39, 0x16);
            this.radioButton1.TabIndex = 0;
            this.radioButton1.TabStop = true;
            this.radioButton1.Text = "Male";
            this.radioButton1.UseVisualStyleBackColor = true;
            this.label1.AutoSize = true;
            this.label1.Location = new Point(13, 0xc5);
            this.label1.Name = "label1";
            this.label1.Size = new Size(0x3a, 0x12);
            this.label1.TabIndex = 15;
            this.label1.Text = "Address";
            this.label4.AutoSize = true;
            this.label4.Location = new Point(13, 0x4f);
            this.label4.Name = "label4";
            this.label4.Size = new Size(0x2d, 0x12);
            this.label4.TabIndex = 13;
            this.label4.Text = "Name";
            this.textBox1.CharacterCasing = CharacterCasing.Upper;
            this.textBox1.Location = new Point(13, 0x2a);
            this.textBox1.Name = "textBox1";
            this.textBox1.Size = new Size(0xfe, 0x19);
            this.textBox1.TabIndex = 12;
            this.label2.AutoSize = true;
            this.label2.Location = new Point(13, 0x15);
            this.label2.Name = "label2";
            this.label2.Size = new Size(0x8b, 0x12);
            this.label2.TabIndex = 11;
            this.label2.Text = "Customer Identity No";
            this.TabPage_EditCustomer.Controls.Add(this.groupBox9);
            this.TabPage_EditCustomer.Controls.Add(this.groupBox5);
            this.TabPage_EditCustomer.Location = new Point(4, 0x1d);
            this.TabPage_EditCustomer.Name = "TabPage_EditCustomer";
            this.TabPage_EditCustomer.Padding = new Padding(3);
            this.TabPage_EditCustomer.Size = new Size(0x4a8, 0x237);
            this.TabPage_EditCustomer.TabIndex = 7;
            this.TabPage_EditCustomer.Text = "Edit Customer";
            this.TabPage_EditCustomer.UseVisualStyleBackColor = true;
            this.groupBox9.Controls.Add(this.textBox13);
            this.groupBox9.Controls.Add(this.label13);
            this.groupBox9.Controls.Add(this.groupBox10);
            this.groupBox9.Controls.Add(this.groupBox11);
            this.groupBox9.Controls.Add(this.textBox14);
            this.groupBox9.Controls.Add(this.label14);
            this.groupBox9.Controls.Add(this.textBox15);
            this.groupBox9.Controls.Add(this.textBox16);
            this.groupBox9.Controls.Add(this.label15);
            this.groupBox9.Controls.Add(this.textBox17);
            this.groupBox9.Controls.Add(this.Btn_Cancel);
            this.groupBox9.Controls.Add(this.Btn_Update);
            this.groupBox9.Controls.Add(this.groupBox12);
            this.groupBox9.Controls.Add(this.label16);
            this.groupBox9.Controls.Add(this.label17);
            this.groupBox9.Controls.Add(this.textBox18);
            this.groupBox9.Controls.Add(this.label18);
            this.groupBox9.Font = new Font("Palatino Linotype", 9.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.groupBox9.Location = new Point(510, 0x10);
            this.groupBox9.Name = "groupBox9";
            this.groupBox9.Size = new Size(0x2a6, 0x1ee);
            this.groupBox9.TabIndex = 3;
            this.groupBox9.TabStop = false;
            this.groupBox9.Text = "Customer Editor Box";
            this.textBox13.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox13.Location = new Point(0x137, 0x107);
            this.textBox13.MaxLength = 10;
            this.textBox13.Name = "textBox13";
            this.textBox13.Size = new Size(0xc7, 0x1d);
            this.textBox13.TabIndex = 0x20;
            this.label13.AutoSize = true;
            this.label13.Location = new Point(0x137, 0xf2);
            this.label13.Name = "label13";
            this.label13.Size = new Size(0xb2, 0x12);
            this.label13.TabIndex = 0x1f;
            this.label13.Text = "Maximu Invoicable Amount";
            this.groupBox10.Controls.Add(this.radioButton13);
            this.groupBox10.Controls.Add(this.radioButton14);
            this.groupBox10.Location = new Point(0x137, 0x9a);
            this.groupBox10.Name = "groupBox10";
            this.groupBox10.Size = new Size(0xc7, 0x48);
            this.groupBox10.TabIndex = 30;
            this.groupBox10.TabStop = false;
            this.groupBox10.Text = "Invoicing Status";
            this.radioButton13.AutoSize = true;
            this.radioButton13.Location = new Point(0x59, 0x23);
            this.radioButton13.Name = "radioButton13";
            this.radioButton13.Size = new Size(0x2d, 0x16);
            this.radioButton13.TabIndex = 1;
            this.radioButton13.TabStop = true;
            this.radioButton13.Text = "No";
            this.radioButton13.UseVisualStyleBackColor = true;
            this.radioButton14.AutoSize = true;
            this.radioButton14.Location = new Point(0x10, 0x23);
            this.radioButton14.Name = "radioButton14";
            this.radioButton14.Size = new Size(0x2f, 0x16);
            this.radioButton14.TabIndex = 0;
            this.radioButton14.TabStop = true;
            this.radioButton14.Text = "Yes";
            this.radioButton14.UseVisualStyleBackColor = true;
            this.groupBox11.Controls.Add(this.radioButton15);
            this.groupBox11.Controls.Add(this.radioButton16);
            this.groupBox11.Location = new Point(0x137, 0x18);
            this.groupBox11.Name = "groupBox11";
            this.groupBox11.Size = new Size(0xc7, 0x6f);
            this.groupBox11.TabIndex = 0x1d;
            this.groupBox11.TabStop = false;
            this.groupBox11.Text = "Customer Type";
            this.radioButton15.AutoSize = true;
            this.radioButton15.Location = new Point(0x10, 0x4d);
            this.radioButton15.Name = "radioButton15";
            this.radioButton15.Size = new Size(0x93, 0x16);
            this.radioButton15.TabIndex = 1;
            this.radioButton15.TabStop = true;
            this.radioButton15.Text = "Company Customer";
            this.radioButton15.UseVisualStyleBackColor = true;
            this.radioButton16.AutoSize = true;
            this.radioButton16.Location = new Point(0x10, 0x23);
            this.radioButton16.Name = "radioButton16";
            this.radioButton16.Size = new Size(0x97, 0x16);
            this.radioButton16.TabIndex = 0;
            this.radioButton16.TabStop = true;
            this.radioButton16.Text = "Individual Customer";
            this.radioButton16.UseVisualStyleBackColor = true;
            this.textBox14.Location = new Point(13, 0x117);
            this.textBox14.Name = "textBox14";
            this.textBox14.Size = new Size(0xfe, 0x19);
            this.textBox14.TabIndex = 0x1c;
            this.label14.AutoSize = true;
            this.label14.Location = new Point(13, 0xc7);
            this.label14.Name = "label14";
            this.label14.Size = new Size(0x2b, 0x12);
            this.label14.TabIndex = 0x1a;
            this.label14.Text = "Email";
            this.textBox15.Location = new Point(13, 220);
            this.textBox15.Name = "textBox15";
            this.textBox15.Size = new Size(0xfe, 0x19);
            this.textBox15.TabIndex = 0x1b;
            this.textBox16.Location = new Point(12, 0xa4);
            this.textBox16.Name = "textBox16";
            this.textBox16.Size = new Size(0xfe, 0x19);
            this.textBox16.TabIndex = 0x19;
            this.label15.AutoSize = true;
            this.label15.Location = new Point(13, 0x8f);
            this.label15.Name = "label15";
            this.label15.Size = new Size(60, 0x12);
            this.label15.TabIndex = 0x18;
            this.label15.Text = "Contacts";
            this.textBox17.Location = new Point(13, 100);
            this.textBox17.Name = "textBox17";
            this.textBox17.Size = new Size(0xfe, 0x19);
            this.textBox17.TabIndex = 0x17;
            this.Btn_Cancel.BackColor = Color.OrangeRed;
            this.Btn_Cancel.FlatStyle = FlatStyle.Flat;
            this.Btn_Cancel.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Btn_Cancel.ForeColor = SystemColors.ButtonHighlight;
            this.Btn_Cancel.Location = new Point(0x4d, 0x14e);
            this.Btn_Cancel.Name = "Btn_Cancel";
            this.Btn_Cancel.Size = new Size(0xb1, 40);
            this.Btn_Cancel.TabIndex = 0x16;
            this.Btn_Cancel.Text = "Cancel";
            this.Btn_Cancel.UseVisualStyleBackColor = false;
            this.Btn_Update.BackColor = Color.Indigo;
            this.Btn_Update.FlatStyle = FlatStyle.Flat;
            this.Btn_Update.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Btn_Update.ForeColor = SystemColors.ButtonHighlight;
            this.Btn_Update.Location = new Point(0x135, 0x14e);
            this.Btn_Update.Name = "Btn_Update";
            this.Btn_Update.Size = new Size(0xc9, 40);
            this.Btn_Update.TabIndex = 20;
            this.Btn_Update.Text = "Update";
            this.Btn_Update.UseVisualStyleBackColor = false;
            this.groupBox12.Controls.Add(this.radioButton17);
            this.groupBox12.Controls.Add(this.radioButton18);
            this.groupBox12.Location = new Point(0x203, 0x18);
            this.groupBox12.Name = "groupBox12";
            this.groupBox12.Size = new Size(0x87, 0x6f);
            this.groupBox12.TabIndex = 0x13;
            this.groupBox12.TabStop = false;
            this.groupBox12.Text = "Customer Gender";
            this.radioButton17.AutoSize = true;
            this.radioButton17.Location = new Point(0x10, 0x4c);
            this.radioButton17.Name = "radioButton17";
            this.radioButton17.Size = new Size(0x47, 0x16);
            this.radioButton17.TabIndex = 1;
            this.radioButton17.TabStop = true;
            this.radioButton17.Text = "Female";
            this.radioButton17.UseVisualStyleBackColor = true;
            this.radioButton18.AutoSize = true;
            this.radioButton18.Location = new Point(0x10, 0x23);
            this.radioButton18.Name = "radioButton18";
            this.radioButton18.Size = new Size(0x39, 0x16);
            this.radioButton18.TabIndex = 0;
            this.radioButton18.TabStop = true;
            this.radioButton18.Text = "Male";
            this.radioButton18.UseVisualStyleBackColor = true;
            this.label16.AutoSize = true;
            this.label16.Location = new Point(13, 0x102);
            this.label16.Name = "label16";
            this.label16.Size = new Size(0x3a, 0x12);
            this.label16.TabIndex = 15;
            this.label16.Text = "Address";
            this.label17.AutoSize = true;
            this.label17.Location = new Point(13, 0x4f);
            this.label17.Name = "label17";
            this.label17.Size = new Size(0x2d, 0x12);
            this.label17.TabIndex = 13;
            this.label17.Text = "Name";
            this.textBox18.CharacterCasing = CharacterCasing.Upper;
            this.textBox18.Location = new Point(13, 0x2a);
            this.textBox18.Name = "textBox18";
            this.textBox18.ReadOnly = true;
            this.textBox18.Size = new Size(0xfe, 0x19);
            this.textBox18.TabIndex = 12;
            this.label18.AutoSize = true;
            this.label18.Location = new Point(13, 0x15);
            this.label18.Name = "label18";
            this.label18.Size = new Size(0x8b, 0x12);
            this.label18.TabIndex = 11;
            this.label18.Text = "Customer Identity No";
            this.groupBox5.Controls.Add(this.panel1);
            this.groupBox5.Controls.Add(this.textBox12);
            this.groupBox5.Controls.Add(this.textBox11);
            this.groupBox5.Controls.Add(this.textBox10);
            this.groupBox5.Controls.Add(this.textBox9);
            this.groupBox5.Controls.Add(this.textBox8);
            this.groupBox5.Controls.Add(this.textBox21);
            this.groupBox5.Controls.Add(this.label21);
            this.groupBox5.Controls.Add(this.textBox20);
            this.groupBox5.Controls.Add(this.label20);
            this.groupBox5.Controls.Add(this.textBox19);
            this.groupBox5.Controls.Add(this.label19);
            this.groupBox5.Controls.Add(this.textBox7);
            this.groupBox5.Controls.Add(this.label7);
            this.groupBox5.Controls.Add(this.label8);
            this.groupBox5.Controls.Add(this.label9);
            this.groupBox5.Controls.Add(this.label10);
            this.groupBox5.Controls.Add(this.label11);
            this.groupBox5.Controls.Add(this.label12);
            this.groupBox5.Dock = DockStyle.Left;
            this.groupBox5.Font = new Font("Palatino Linotype", 9.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.groupBox5.Location = new Point(3, 3);
            this.groupBox5.Name = "groupBox5";
            this.groupBox5.Size = new Size(0x1e7, 0x231);
            this.groupBox5.TabIndex = 2;
            this.groupBox5.TabStop = false;
            this.groupBox5.Text = "Customer Editor Box";
            this.panel1.Controls.Add(this.Btn_Search);
            this.panel1.Controls.Add(this.label22);
            this.panel1.Controls.Add(this.textBox22);
            this.panel1.Location = new Point(6, 0x18);
            this.panel1.Name = "panel1";
            this.panel1.Size = new Size(460, 0x4e);
            this.panel1.TabIndex = 0x2c;
            this.Btn_Search.BackColor = Color.OrangeRed;
            this.Btn_Search.FlatStyle = FlatStyle.Flat;
            this.Btn_Search.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Btn_Search.ForeColor = SystemColors.ButtonHighlight;
            this.Btn_Search.Location = new Point(0xd7, 0x10);
            this.Btn_Search.Name = "Btn_Search";
            this.Btn_Search.Size = new Size(0x9a, 40);
            this.Btn_Search.TabIndex = 0x17;
            this.Btn_Search.Text = "Search";
            this.Btn_Search.UseVisualStyleBackColor = false;
            this.label22.AutoSize = true;
            this.label22.Location = new Point(7, 10);
            this.label22.Name = "label22";
            this.label22.Size = new Size(0x8b, 0x12);
            this.label22.TabIndex = 12;
            this.label22.Text = "Customer Identity No";
            this.textBox22.Location = new Point(10, 0x1f);
            this.textBox22.Name = "textBox22";
            this.textBox22.Size = new Size(160, 0x19);
            this.textBox22.TabIndex = 0;
            this.textBox12.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox12.Location = new Point(0x10, 0x16e);
            this.textBox12.MaxLength = 10;
            this.textBox12.Name = "textBox12";
            this.textBox12.ReadOnly = true;
            this.textBox12.Size = new Size(0xc7, 0x1d);
            this.textBox12.TabIndex = 0x2b;
            this.textBox12.TextAlign = HorizontalAlignment.Center;
            this.textBox11.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox11.Location = new Point(0x10, 0x133);
            this.textBox11.MaxLength = 10;
            this.textBox11.Name = "textBox11";
            this.textBox11.ReadOnly = true;
            this.textBox11.Size = new Size(0xc7, 0x1d);
            this.textBox11.TabIndex = 0x2a;
            this.textBox11.TextAlign = HorizontalAlignment.Center;
            this.textBox10.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox10.Location = new Point(0x10, 250);
            this.textBox10.MaxLength = 10;
            this.textBox10.Name = "textBox10";
            this.textBox10.ReadOnly = true;
            this.textBox10.Size = new Size(0xc7, 0x1d);
            this.textBox10.TabIndex = 0x29;
            this.textBox10.TextAlign = HorizontalAlignment.Center;
            this.textBox9.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox9.Location = new Point(0x10, 0xc1);
            this.textBox9.MaxLength = 10;
            this.textBox9.Name = "textBox9";
            this.textBox9.ReadOnly = true;
            this.textBox9.Size = new Size(0xc7, 0x1d);
            this.textBox9.TabIndex = 40;
            this.textBox9.TextAlign = HorizontalAlignment.Center;
            this.textBox8.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox8.Location = new Point(0x10, 0x81);
            this.textBox8.MaxLength = 10;
            this.textBox8.Name = "textBox8";
            this.textBox8.ReadOnly = true;
            this.textBox8.Size = new Size(0xc7, 0x1d);
            this.textBox8.TabIndex = 0x27;
            this.textBox8.TextAlign = HorizontalAlignment.Center;
            this.textBox21.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox21.Location = new Point(0x10b, 0xfb);
            this.textBox21.MaxLength = 10;
            this.textBox21.Name = "textBox21";
            this.textBox21.ReadOnly = true;
            this.textBox21.Size = new Size(0xc7, 0x1d);
            this.textBox21.TabIndex = 0x26;
            this.textBox21.TextAlign = HorizontalAlignment.Center;
            this.label21.AutoSize = true;
            this.label21.Location = new Point(0x10b, 230);
            this.label21.Name = "label21";
            this.label21.Size = new Size(0x6c, 0x12);
            this.label21.TabIndex = 0x25;
            this.label21.Text = "Invoicable Staus";
            this.textBox20.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox20.Location = new Point(0x10b, 0xc1);
            this.textBox20.MaxLength = 10;
            this.textBox20.Name = "textBox20";
            this.textBox20.ReadOnly = true;
            this.textBox20.Size = new Size(0xc7, 0x1d);
            this.textBox20.TabIndex = 0x24;
            this.textBox20.TextAlign = HorizontalAlignment.Center;
            this.label20.AutoSize = true;
            this.label20.Location = new Point(0x108, 0xac);
            this.label20.Name = "label20";
            this.label20.Size = new Size(0x36, 0x12);
            this.label20.TabIndex = 0x23;
            this.label20.Text = "Gender";
            this.textBox19.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox19.Location = new Point(0x10b, 0x81);
            this.textBox19.MaxLength = 10;
            this.textBox19.Name = "textBox19";
            this.textBox19.ReadOnly = true;
            this.textBox19.Size = new Size(0xc7, 0x1d);
            this.textBox19.TabIndex = 0x22;
            this.textBox19.TextAlign = HorizontalAlignment.Center;
            this.label19.AutoSize = true;
            this.label19.Location = new Point(0x10b, 0x69);
            this.label19.Name = "label19";
            this.label19.Size = new Size(0x65, 0x12);
            this.label19.TabIndex = 0x21;
            this.label19.Text = "Customer Type";
            this.textBox7.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox7.Location = new Point(0x10b, 0x134);
            this.textBox7.MaxLength = 10;
            this.textBox7.Name = "textBox7";
            this.textBox7.ReadOnly = true;
            this.textBox7.Size = new Size(0xc7, 0x1d);
            this.textBox7.TabIndex = 0x20;
            this.textBox7.TextAlign = HorizontalAlignment.Center;
            this.label7.AutoSize = true;
            this.label7.Location = new Point(0x10b, 0x121);
            this.label7.Name = "label7";
            this.label7.Size = new Size(0xb2, 0x12);
            this.label7.TabIndex = 0x1f;
            this.label7.Text = "Maximu Invoicable Amount";
            this.label8.AutoSize = true;
            this.label8.Location = new Point(13, 0x11a);
            this.label8.Name = "label8";
            this.label8.Size = new Size(0x2b, 0x12);
            this.label8.TabIndex = 0x1a;
            this.label8.Text = "Email";
            this.label9.AutoSize = true;
            this.label9.Location = new Point(13, 0xe2);
            this.label9.Name = "label9";
            this.label9.Size = new Size(60, 0x12);
            this.label9.TabIndex = 0x18;
            this.label9.Text = "Contacts";
            this.label10.AutoSize = true;
            this.label10.Location = new Point(13, 0x155);
            this.label10.Name = "label10";
            this.label10.Size = new Size(0x3a, 0x12);
            this.label10.TabIndex = 15;
            this.label10.Text = "Address";
            this.label11.AutoSize = true;
            this.label11.Location = new Point(13, 0xac);
            this.label11.Name = "label11";
            this.label11.Size = new Size(0x2d, 0x12);
            this.label11.TabIndex = 13;
            this.label11.Text = "Name";
            this.label12.AutoSize = true;
            this.label12.Location = new Point(13, 0x69);
            this.label12.Name = "label12";
            this.label12.Size = new Size(0x8b, 0x12);
            this.label12.TabIndex = 11;
            this.label12.Text = "Customer Identity No";
            this.Tab_Page_CustomerAccount.Controls.Add(this.panel3);
            this.Tab_Page_CustomerAccount.Location = new Point(4, 0x1d);
            this.Tab_Page_CustomerAccount.Name = "Tab_Page_CustomerAccount";
            this.Tab_Page_CustomerAccount.Padding = new Padding(3);
            this.Tab_Page_CustomerAccount.Size = new Size(0x4a8, 0x237);
            this.Tab_Page_CustomerAccount.TabIndex = 9;
            this.Tab_Page_CustomerAccount.Text = "Customer Account";
            this.Tab_Page_CustomerAccount.UseVisualStyleBackColor = true;
            this.panel3.Controls.Add(this.groupBox6);
            this.panel3.Controls.Add(this.panel2);
            this.panel3.Dock = DockStyle.Left;
            this.panel3.Location = new Point(3, 3);
            this.panel3.Name = "panel3";
            this.panel3.Size = new Size(490, 0x231);
            this.panel3.TabIndex = 0x2e;
            this.groupBox6.Controls.Add(this.textBox25);
            this.groupBox6.Controls.Add(this.textBox26);
            this.groupBox6.Controls.Add(this.textBox27);
            this.groupBox6.Controls.Add(this.textBox28);
            this.groupBox6.Controls.Add(this.textBox29);
            this.groupBox6.Controls.Add(this.textBox30);
            this.groupBox6.Controls.Add(this.label25);
            this.groupBox6.Controls.Add(this.textBox31);
            this.groupBox6.Controls.Add(this.label26);
            this.groupBox6.Controls.Add(this.textBox32);
            this.groupBox6.Controls.Add(this.label27);
            this.groupBox6.Controls.Add(this.textBox33);
            this.groupBox6.Controls.Add(this.label28);
            this.groupBox6.Controls.Add(this.label29);
            this.groupBox6.Controls.Add(this.label30);
            this.groupBox6.Controls.Add(this.label31);
            this.groupBox6.Controls.Add(this.label32);
            this.groupBox6.Controls.Add(this.label33);
            this.groupBox6.Dock = DockStyle.Top;
            this.groupBox6.Font = new Font("Palatino Linotype", 9.75f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.groupBox6.Location = new Point(0, 70);
            this.groupBox6.Name = "groupBox6";
            this.groupBox6.Size = new Size(490, 0x152);
            this.groupBox6.TabIndex = 0x2e;
            this.groupBox6.TabStop = false;
            this.groupBox6.Text = "Customer Editor Box";
            this.textBox25.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox25.Location = new Point(11, 0x121);
            this.textBox25.MaxLength = 10;
            this.textBox25.Name = "textBox25";
            this.textBox25.ReadOnly = true;
            this.textBox25.Size = new Size(0xeb, 0x1d);
            this.textBox25.TabIndex = 0x2b;
            this.textBox25.TextAlign = HorizontalAlignment.Center;
            this.textBox26.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox26.Location = new Point(11, 230);
            this.textBox26.MaxLength = 10;
            this.textBox26.Name = "textBox26";
            this.textBox26.ReadOnly = true;
            this.textBox26.Size = new Size(0xeb, 0x1d);
            this.textBox26.TabIndex = 0x2a;
            this.textBox26.TextAlign = HorizontalAlignment.Center;
            this.textBox27.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox27.Location = new Point(11, 0xad);
            this.textBox27.MaxLength = 10;
            this.textBox27.Name = "textBox27";
            this.textBox27.ReadOnly = true;
            this.textBox27.Size = new Size(0xeb, 0x1d);
            this.textBox27.TabIndex = 0x29;
            this.textBox27.TextAlign = HorizontalAlignment.Center;
            this.textBox28.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox28.Location = new Point(11, 0x74);
            this.textBox28.MaxLength = 10;
            this.textBox28.Name = "textBox28";
            this.textBox28.ReadOnly = true;
            this.textBox28.Size = new Size(0xeb, 0x1d);
            this.textBox28.TabIndex = 40;
            this.textBox28.TextAlign = HorizontalAlignment.Center;
            this.textBox29.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox29.Location = new Point(11, 0x34);
            this.textBox29.MaxLength = 10;
            this.textBox29.Name = "textBox29";
            this.textBox29.ReadOnly = true;
            this.textBox29.Size = new Size(0xeb, 0x1d);
            this.textBox29.TabIndex = 0x27;
            this.textBox29.TextAlign = HorizontalAlignment.Center;
            this.textBox30.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox30.Location = new Point(0x106, 0xae);
            this.textBox30.MaxLength = 10;
            this.textBox30.Name = "textBox30";
            this.textBox30.ReadOnly = true;
            this.textBox30.Size = new Size(0xc7, 0x1d);
            this.textBox30.TabIndex = 0x26;
            this.textBox30.TextAlign = HorizontalAlignment.Center;
            this.label25.AutoSize = true;
            this.label25.Location = new Point(0x106, 0x99);
            this.label25.Name = "label25";
            this.label25.Size = new Size(0x6c, 0x12);
            this.label25.TabIndex = 0x25;
            this.label25.Text = "Invoicable Staus";
            this.textBox31.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox31.Location = new Point(0x106, 0x74);
            this.textBox31.MaxLength = 10;
            this.textBox31.Name = "textBox31";
            this.textBox31.ReadOnly = true;
            this.textBox31.Size = new Size(0xc7, 0x1d);
            this.textBox31.TabIndex = 0x24;
            this.textBox31.TextAlign = HorizontalAlignment.Center;
            this.label26.AutoSize = true;
            this.label26.Location = new Point(0x103, 0x5f);
            this.label26.Name = "label26";
            this.label26.Size = new Size(0x36, 0x12);
            this.label26.TabIndex = 0x23;
            this.label26.Text = "Gender";
            this.textBox32.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox32.Location = new Point(0x106, 0x34);
            this.textBox32.MaxLength = 10;
            this.textBox32.Name = "textBox32";
            this.textBox32.ReadOnly = true;
            this.textBox32.Size = new Size(0xc7, 0x1d);
            this.textBox32.TabIndex = 0x22;
            this.textBox32.TextAlign = HorizontalAlignment.Center;
            this.label27.AutoSize = true;
            this.label27.Location = new Point(0x106, 0x1c);
            this.label27.Name = "label27";
            this.label27.Size = new Size(0x65, 0x12);
            this.label27.TabIndex = 0x21;
            this.label27.Text = "Customer Type";
            this.textBox33.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.textBox33.Location = new Point(0x106, 0xe7);
            this.textBox33.MaxLength = 10;
            this.textBox33.Name = "textBox33";
            this.textBox33.ReadOnly = true;
            this.textBox33.Size = new Size(0xc7, 0x1d);
            this.textBox33.TabIndex = 0x20;
            this.textBox33.TextAlign = HorizontalAlignment.Center;
            this.label28.AutoSize = true;
            this.label28.Location = new Point(0x106, 0xd4);
            this.label28.Name = "label28";
            this.label28.Size = new Size(0xb2, 0x12);
            this.label28.TabIndex = 0x1f;
            this.label28.Text = "Maximu Invoicable Amount";
            this.label29.AutoSize = true;
            this.label29.Location = new Point(8, 0xcd);
            this.label29.Name = "label29";
            this.label29.Size = new Size(0x2b, 0x12);
            this.label29.TabIndex = 0x1a;
            this.label29.Text = "Email";
            this.label30.AutoSize = true;
            this.label30.Location = new Point(8, 0x95);
            this.label30.Name = "label30";
            this.label30.Size = new Size(60, 0x12);
            this.label30.TabIndex = 0x18;
            this.label30.Text = "Contacts";
            this.label31.AutoSize = true;
            this.label31.Location = new Point(8, 0x108);
            this.label31.Name = "label31";
            this.label31.Size = new Size(0x3a, 0x12);
            this.label31.TabIndex = 15;
            this.label31.Text = "Address";
            this.label32.AutoSize = true;
            this.label32.Location = new Point(8, 0x5f);
            this.label32.Name = "label32";
            this.label32.Size = new Size(0x2d, 0x12);
            this.label32.TabIndex = 13;
            this.label32.Text = "Name";
            this.label33.AutoSize = true;
            this.label33.Location = new Point(8, 0x1c);
            this.label33.Name = "label33";
            this.label33.Size = new Size(0x8b, 0x12);
            this.label33.TabIndex = 11;
            this.label33.Text = "Customer Identity No";
            this.panel2.Controls.Add(this.Btn_searchAccount);
            this.panel2.Controls.Add(this.label23);
            this.panel2.Controls.Add(this.textBox23);
            this.panel2.Dock = DockStyle.Top;
            this.panel2.Location = new Point(0, 0);
            this.panel2.Name = "panel2";
            this.panel2.Size = new Size(490, 70);
            this.panel2.TabIndex = 0x2d;
            this.Btn_searchAccount.BackColor = Color.OrangeRed;
            this.Btn_searchAccount.FlatStyle = FlatStyle.Flat;
            this.Btn_searchAccount.Font = new Font("Palatino Linotype", 12f, FontStyle.Bold, GraphicsUnit.Point, 0);
            this.Btn_searchAccount.ForeColor = SystemColors.ButtonHighlight;
            this.Btn_searchAccount.Location = new Point(0xd7, 0x10);
            this.Btn_searchAccount.Name = "Btn_searchAccount";
            this.Btn_searchAccount.Size = new Size(0x9a, 40);
            this.Btn_searchAccount.TabIndex = 0x17;
            this.Btn_searchAccount.Text = "Search";
            this.Btn_searchAccount.UseVisualStyleBackColor = false;
            this.label23.AutoSize = true;
            this.label23.Location = new Point(7, 10);
            this.label23.Name = "label23";
            this.label23.Size = new Size(0x8b, 0x11);
            this.label23.TabIndex = 12;
            this.label23.Text = "Customer Identity No";
            this.textBox23.Location = new Point(10, 0x1f);
            this.textBox23.Name = "textBox23";
            this.textBox23.Size = new Size(160, 0x17);
            this.textBox23.TabIndex = 0;
            this.TabPage_CustomersList.Controls.Add(this.dataGridView1);
            this.TabPage_CustomersList.Controls.Add(this.panel6);
            this.TabPage_CustomersList.Controls.Add(this.panel5);
            this.TabPage_CustomersList.Location = new Point(4, 0x1d);
            this.TabPage_CustomersList.Name = "TabPage_CustomersList";
            this.TabPage_CustomersList.Padding = new Padding(3);
            this.TabPage_CustomersList.Size = new Size(0x4a8, 0x237);
            this.TabPage_CustomersList.TabIndex = 11;
            this.TabPage_CustomersList.Text = "Invoiced Customers List";
            this.TabPage_CustomersList.UseVisualStyleBackColor = true;
            this.dataGridView1.AllowUserToAddRows = false;
            this.dataGridView1.AllowUserToDeleteRows = false;
            this.dataGridView1.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
            this.dataGridView1.BackgroundColor = SystemColors.Control;
            this.dataGridView1.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            DataGridViewColumn[] dataGridViewColumns = new DataGridViewColumn[10];
            dataGridViewColumns[0] = this.Column1;
            dataGridViewColumns[1] = this.Column2;
            dataGridViewColumns[2] = this.Column3;
            dataGridViewColumns[3] = this.Column4;
            dataGridViewColumns[4] = this.Column5;
            dataGridViewColumns[5] = this.Column6;
            dataGridViewColumns[6] = this.Column7;
            dataGridViewColumns[7] = this.Column8;
            dataGridViewColumns[8] = this.Column9;
            dataGridViewColumns[9] = this.Column10;
            this.dataGridView1.Columns.AddRange(dataGridViewColumns);
            this.dataGridView1.Dock = DockStyle.Fill;
            this.dataGridView1.Location = new Point(3, 0x58);
            this.dataGridView1.Name = "dataGridView1";
            this.dataGridView1.ReadOnly = true;
            this.dataGridView1.RowHeadersVisible = false;
            this.dataGridView1.Size = new Size(0x4a2, 0x1a5);
            this.dataGridView1.TabIndex = 3;
            this.Column1.HeaderText = "IDNo";
            this.Column1.Name = "Column1";
            this.Column1.ReadOnly = true;
            this.Column2.HeaderText = "CustType";
            this.Column2.Name = "Column2";
            this.Column2.ReadOnly = true;
            this.Column3.HeaderText = "Name";
            this.Column3.Name = "Column3";
            this.Column3.ReadOnly = true;
            this.Column4.HeaderText = "Gender";
            this.Column4.Name = "Column4";
            this.Column4.ReadOnly = true;
            this.Column5.HeaderText = "Amount";
            this.Column5.Name = "Column5";
            this.Column5.ReadOnly = true;
            this.Column6.HeaderText = "Phone";
            this.Column6.Name = "Column6";
            this.Column6.ReadOnly = true;
            this.Column7.HeaderText = "Email";
            this.Column7.Name = "Column7";
            this.Column7.ReadOnly = true;
            this.Column8.HeaderText = "Address";
            this.Column8.Name = "Column8";
            this.Column8.ReadOnly = true;
            this.Column9.HeaderText = "Status";
            this.Column9.Name = "Column9";
            this.Column9.ReadOnly = true;
            this.Column10.HeaderText = "RegDate";
            this.Column10.Name = "Column10";
            this.Column10.ReadOnly = true;
            this.panel6.Controls.Add(this.Btn_RefreshInvoiced_Customers);
            this.panel6.Dock = DockStyle.Top;
            this.panel6.Location = new Point(3, 3);
            this.panel6.Name = "panel6";
            this.panel6.Size = new Size(0x4a2, 0x55);
            this.panel6.TabIndex = 2;
            this.panel5.Dock = DockStyle.Bottom;
            this.panel5.Location = new Point(3, 0x1fd);
            this.panel5.Name = "panel5";
            this.panel5.Size = new Size(0x4a2, 0x37);
            this.panel5.TabIndex = 1;
            this.Btn_RefreshInvoiced_Customers.Location = new Point(0x41, 0x20);
            this.Btn_RefreshInvoiced_Customers.Name = "Btn_RefreshInvoiced_Customers";
            this.Btn_RefreshInvoiced_Customers.Size = new Size(0xc7, 0x1c);
            this.Btn_RefreshInvoiced_Customers.TabIndex = 0;
            this.Btn_RefreshInvoiced_Customers.Text = "Refresh Customers List";
            this.Btn_RefreshInvoiced_Customers.UseVisualStyleBackColor = true;
            this.Btn_RefreshInvoiced_Customers.Click += new EventHandler(this.Btn_RefreshInvoiced_Customers_Click);
            base.AutoScaleDimensions = new SizeF(6f, 13f);
            base.AutoScaleMode = AutoScaleMode.Font;
            this.BackColor = SystemColors.ButtonHighlight;
            base.Controls.Add(this.TabControl_ManageCustomers);
            base.Name = "InvoicedCustomers";
            base.Size = new Size(0x4b0, 600);
            this.TabControl_ManageCustomers.ResumeLayout(false);
            this.TabPage_NewCustomer.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.groupBox4.ResumeLayout(false);
            this.groupBox4.PerformLayout();
            this.groupBox3.ResumeLayout(false);
            this.groupBox3.PerformLayout();
            this.groupBox2.ResumeLayout(false);
            this.groupBox2.PerformLayout();
            this.TabPage_EditCustomer.ResumeLayout(false);
            this.groupBox9.ResumeLayout(false);
            this.groupBox9.PerformLayout();
            this.groupBox10.ResumeLayout(false);
            this.groupBox10.PerformLayout();
            this.groupBox11.ResumeLayout(false);
            this.groupBox11.PerformLayout();
            this.groupBox12.ResumeLayout(false);
            this.groupBox12.PerformLayout();
            this.groupBox5.ResumeLayout(false);
            this.groupBox5.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.panel1.PerformLayout();
            this.Tab_Page_CustomerAccount.ResumeLayout(false);
            this.panel3.ResumeLayout(false);
            this.groupBox6.ResumeLayout(false);
            this.groupBox6.PerformLayout();
            this.panel2.ResumeLayout(false);
            this.panel2.PerformLayout();
            this.TabPage_CustomersList.ResumeLayout(false);
            ((ISupportInitialize) this.dataGridView1).EndInit();
            this.panel6.ResumeLayout(false);
            base.ResumeLayout(false);
        }

        public void InsertCustomer()
        {
            try
            {
                MySqlConnection connection = new MySqlConnection(this.Db.DBConnecString());
                connection.Open();
                MySqlCommand command = new MySqlCommand("INSERT INTO customersinvoiced (IdNumber, CustomerType, Name, Gender, MaxAmount, Phone, Email, Address, InvoiceStatus, RegDate, Counter, UserId) VALUES(@IdNumber, @CustomerType, @Name, @Gender, @MaxAmount, @Phone, @Email,@Address, @InvoiceStatus, @RegDate, @Counter, @UserId);", connection);
                command.Parameters.AddWithValue("@IdNumber", this.textBox1.Text.Trim());
                if (this.radioButton6.Checked)
                {
                    command.Parameters.AddWithValue("@CustomerType", "Individual");
                }
                if (this.radioButton5.Checked)
                {
                    command.Parameters.AddWithValue("@CustomerType", "Company");
                }
                if (this.radioButton1.Checked)
                {
                    command.Parameters.AddWithValue("@Gender", "Male");
                }
                if (this.radioButton2.Checked)
                {
                    command.Parameters.AddWithValue("@Gender", "Female");
                }
                if (this.radioButton4.Checked)
                {
                    command.Parameters.AddWithValue("@InvoiceStatus", 1);
                }
                if (this.radioButton3.Checked)
                {
                    command.Parameters.AddWithValue("@InvoiceStatus", 0);
                }
                command.Parameters.AddWithValue("@Name", this.textBox2.Text.Trim());
                command.Parameters.AddWithValue("@Phone", this.textBox1.Text.Trim());
                command.Parameters.AddWithValue("@Email", this.textBox4.Text.Trim());
                command.Parameters.AddWithValue("@Address", this.textBox5.Text.Trim());
                command.Parameters.AddWithValue("@MaxAmount", this.textBox6.Text.Trim());
                command.Parameters.AddWithValue("@RegDate", Program.CurrentDateTime());
                command.Parameters.AddWithValue("@Counter", Program.LogInCounter);
                command.Parameters.AddWithValue("@UserId", Program.CurrLoggedInUser.UserID);
                if (command.ExecuteNonQuery() > 0)
                {
                    MessageBox.Show("You have successfully registered the Customer", "SUCCESS", MessageBoxButtons.OK);
                }
                else
                {
                    MessageBox.Show("failed to register the Customer", "Regitrastion failed", MessageBoxButtons.OK, MessageBoxIcon.Exclamation);
                }
                connection.Close();
            }
            catch (Exception exception)
            {
                MessageBox.Show(exception.Message + exception.StackTrace, "ERROR MESSAGE", MessageBoxButtons.OK);
            }
        }

        private void LoadInvoicedCustomers()
        {
            try
            {
                this.dataGridView1.Rows.Clear();
                MySqlConnection connection = new MySqlConnection(this.Db.DBConnecString());
                connection.Open();
                MySqlCommand command = connection.CreateCommand();
                command.CommandText = "SELECT * from customersinvoiced;";
                MySqlDataReader reader = command.ExecuteReader();
                if (!reader.HasRows)
                {
                    MessageBox.Show("No invoiced Customers Found!", "MessageBox", MessageBoxButtons.OK, MessageBoxIcon.Asterisk);
                }
                else
                {
                    while (true)
                    {
                        if (!reader.Read())
                        {
                            break;
                        }
                        object[] values = new object[10];
                        values[0] = reader.GetString("IdNumber");
                        values[1] = reader.GetString("CustomerType");
                        values[2] = reader.GetString("Name");
                        values[3] = reader.GetString("Gender");
                        values[4] = reader.GetString("MaxAmount");
                        values[5] = reader.GetString("Phone");
                        values[6] = reader.GetString("Email");
                        values[7] = reader.GetString("Address");
                        values[8] = reader.GetString("InvoiceStatus");
                        values[9] = reader.GetString("RegDate");
                        this.dataGridView1.Rows.Add(values);
                    }
                }
                connection.Close();
            }
            catch (Exception exception1)
            {
                MessageBox.Show(exception1.Message, "Error Message", MessageBoxButtons.OK, MessageBoxIcon.Hand);
            }
        }

        private void TabControl_ManageCustomers_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (this.TabControl_ManageCustomers.SelectedTab.Name == "TabPage_CustomersList")
            {
                this.LoadInvoicedCustomers();
            }
        }
    }
}

